"""
agents/explainer.py
--------------------
Agent 6: Explainer

Generates a formal reason letter in both English and Hindi.

FIX — Async node incompatibility with graph.stream():
  The original was `async def explainer_node(...)`.
  LangGraph 1.x raises TypeError when an async node is called via the
  SYNCHRONOUS graph.stream() / graph.invoke() API:
    "No synchronous function provided to 'explainer'. Either initialize
     with a synchronous function or invoke via the async API."

  Verified against langgraph==1.2.4.

  Fix: Make the node sync and wrap asyncio.gather() inside asyncio.run().
  asyncio.run() creates a fresh event loop, runs the coroutine to
  completion, and tears it down — safe to call from a sync context
  (Streamlit runs in a sync thread by default).

  The parallel LLM calls are preserved — English and Hindi letters
  are still generated concurrently, cutting latency in half vs sequential.

  ADDITIONAL FIX — asyncio.run() inside a running event loop:
  asyncio.run() raises RuntimeError if called from pytest-asyncio, Jupyter,
  or any other context that already has a running event loop.

  How this guard actually works:
    Streamlit runs each script execution in a dedicated OS thread
    (ScriptRunner.scriptThread). That thread has NO event loop of its own —
    it is separate from Tornado's main-thread loop. So asyncio.get_running_loop()
    raises RuntimeError("no running event loop") inside the Streamlit thread,
    and asyncio.run() succeeds there.

    pytest-asyncio and Jupyter DO have a running loop on the calling thread,
    so asyncio.get_running_loop() succeeds, and we fall through to the
    ThreadPoolExecutor path where asyncio.run() runs in a fresh OS thread
    that has no parent loop.

  The net result: asyncio.run() is used in Streamlit (correct), and
  ThreadPoolExecutor is used in pytest-asyncio / Jupyter (also correct).

HINDI QUALITY VERIFICATION — deterministic Python checks:
  The Hindi letter is generated by prompting LLaMA 3.3-70B with a Hindi
  prompt. LLMs can produce grammatically plausible but factually wrong
  output (e.g. wrong decision word, untranslated placeholders, code-switching
  to English mid-sentence) without any external signal of failure.

  In a BFSI context the Hindi letter is a regulatory document under RBI's
  Fair Lending guidelines, so silent quality failures are not acceptable.

  Fix: after generating the Hindi letter, deterministic Python checks
  verify four properties without an extra LLM call:
    1. >= 30% of non-whitespace characters are Devanagari (Unicode U+0900–U+097F).
       This tolerates English names and financial terms (CIBIL, FOIR) mixed in
       naturally, while catching a fully-English accidental output (~0% ratio).
    2. The correct decision word appears (अनुमोदित / अस्वीकृत / समीक्षाधीन).
    3. No unreplaced {brace} template placeholders remain.
    4. No unreplaced [bracket] template placeholders remain.

  A name post-processing step runs BEFORE the quality check, replacing
  [आपका नाम] and common variants with the actual applicant name.
  This handles a recurring LLaMA 3.3-70B behaviour where the model outputs
  a template placeholder instead of substituting the name from the prompt.

  On failure, the fallback template is substituted. The fallback does not
  re-call the LLM (no latency added on the failure path).

  Why Python instead of LLM-as-judge:
    The LLM judge was consistently failing correct letters by inventing
    reasons not in the criteria (e.g. rejecting English proper nouns in
    signatures, insisting names be transliterated to Devanagari). Deterministic
    checks are reliable for these objective properties and remove the extra
    LLM call and rate-limit exposure.

  Interview note: "The explainer agent mirrors real regulatory requirements —
  RBI's Fair Lending guidelines require lenders to communicate rejection
  reasons clearly and in the applicant's preferred language."
"""
import asyncio
import concurrent.futures
import logging
import re

from langchain_core.messages import HumanMessage

from state import UnderwritingState
from utils.llm import get_llm

logger = logging.getLogger(__name__)


_EXPLAINER_PROMPT_EN = """You are a senior credit officer at an Indian NBFC writing a formal loan decision letter.

APPLICANT: {name}
DECISION: {decision}
LOAN REQUESTED: ₹{loan_amount:,.0f} for {purpose}
REASONS: {reasons}

Write a formal but empathetic English letter (150–200 words) that:
- Addresses the applicant by their full name ({name}) in the salutation
- States the decision clearly in the first sentence
- Explains each reason using its exact technical term as given above (e.g. CIBIL score,
  FOIR) — do not paraphrase or substitute these terms with generic alternatives
- For Approve: mentions next steps (document verification, disbursement timeline)
- For Reject: provides specific improvement advice (e.g. "improve CIBIL score to 700+")
- Ends with contact information and a courteous closing

Return ONLY the letter text, no JSON, no preamble."""

_EXPLAINER_PROMPT_HI = """आप एक भारतीय NBFC में वरिष्ठ ऋण अधिकारी हैं और एक औपचारिक ऋण निर्णय पत्र लिख रहे हैं।

आवेदक: {name}
निर्णय: {decision_hi}
अनुरोधित ऋण: ₹{loan_amount:,.0f} ({purpose} के लिए)
निर्णय के मुख्य कारण (इन्हें हिंदी में समझाएं): {reasons}

एक औपचारिक हिंदी पत्र लिखें (100–150 शब्द) जो:
- संबोधन में आवेदक का पूरा नाम ({name}) का उपयोग करे — कोई placeholder जैसे [आपका नाम] नहीं
- पहले वाक्य में निर्णय स्पष्ट रूप से बताए
- प्रत्येक कारण को ऊपर दिए गए तकनीकी शब्दों (जैसे CIBIL स्कोर, FOIR) का उपयोग करते हुए समझाए
- अनुमोदन के लिए: अगले चरण बताए (दस्तावेज़ सत्यापन, वितरण समयसीमा)
- अस्वीकृति के लिए: सुधार की विशिष्ट सलाह दे
- विनम्र समापन के साथ समाप्त हो

केवल पत्र का पाठ लौटाएं, JSON या प्रस्तावना नहीं।"""

_DECISION_HI = {
    "Approve": "अनुमोदित",
    "Reject": "अस्वीकृत",
    "Refer": "समीक्षाधीन",
}

# Minimal guaranteed-correct Hindi fallback templates.
# Used when deterministic quality checks detect a failure in the generated letter.
# These are short but legally sufficient: they state the decision clearly
# in Devanagari and invite the applicant to contact the branch.
_HINDI_FALLBACK = {
    "Approve": (
        "प्रिय आवेदक,\n\n"
        "हमें यह सूचित करते हुए प्रसन्नता है कि आपका ऋण आवेदन **अनुमोदित** कर दिया गया है।\n"
        "कृपया दस्तावेज़ सत्यापन के लिए निकटतम शाखा में संपर्क करें।\n\n"
        "धन्यवाद।\n— ऋण विभाग"
    ),
    "Reject": (
        "प्रिय आवेदक,\n\n"
        "खेद है कि आपका ऋण आवेदन **अस्वीकृत** कर दिया गया है।\n"
        "कारण: पात्रता मानदंड पूर्ण नहीं हुए। अधिक जानकारी के लिए शाखा में संपर्क करें।\n\n"
        "धन्यवाद।\n— ऋण विभाग"
    ),
    "Refer": (
        "प्रिय आवेदक,\n\n"
        "आपका ऋण आवेदन **समीक्षाधीन** है। एक वरिष्ठ अधिकारी आपसे संपर्क करेंगे।\n\n"
        "धन्यवाद।\n— ऋण विभाग"
    ),
}


def _verify_hindi_quality(letter_hi: str, decision: str) -> tuple[bool, str]:
    """
    Verify Hindi letter quality with deterministic Python checks.

    Replaces the LLM-as-judge approach. The judge was inconsistently failing
    correct letters because LLaMA 3.3-70B invented reasons not present in the
    criteria (e.g. rejecting English proper nouns in signatures, requiring
    transliteration of applicant names). Deterministic checks are more reliable
    for these objective properties and avoid the extra LLM call and latency.

    Four checks (all must pass):
      1. Devanagari character ratio >= 30% of non-whitespace characters.
         Counts Unicode block U+0900–U+097F. A real Hindi letter scores ~70–90%
         even when mixed with English names (Rahul Sharma) and financial terms
         (CIBIL, FOIR). An accidentally-English letter scores ~0%.
         The 30% threshold is a safe midpoint that tolerates heavy mixing.
         Reference: Unicode Devanagari block — https://unicode.org/charts/PDF/U0900.pdf

      2. Correct Hindi decision word present (अनुमोदित / अस्वीकृत / समीक्षाधीन).
         Simple string membership check — deterministic.

      3. No {brace} template placeholders remain (e.g. {name}, {decision}).
         Caught by regex \\{[a-zA-Z_]+\\}.

      4. No [bracket] template placeholders remain (e.g. [आपका नाम], [निर्णय]).
         Caught by regex \\[[^\\]]{1,40}\\].
         Note: the name post-processing step before this call already replaces
         [आपका नाम] with the real name, so this check is a safety net for any
         remaining bracket placeholders the pre-processing didn't cover.

    Returns (passed: bool, reason: str).
    """
    # Check 1: Devanagari character ratio
    non_ws = [c for c in letter_hi if not c.isspace()]
    if not non_ws:
        return False, "Letter is empty."
    devanagari = sum(1 for c in non_ws if "\u0900" <= c <= "\u097F")
    ratio = devanagari / len(non_ws)
    if ratio < 0.30:
        return False, (
            f"Too few Devanagari characters ({ratio:.0%}) — "
            "letter may be in wrong script."
        )

    # Check 2: Correct decision word present
    expected_word = _DECISION_HI.get(decision, "")
    if expected_word and expected_word not in letter_hi:
        return False, f'Decision word "{expected_word}" not found in letter.'

    # Check 3: No {{brace}} template placeholders
    brace_placeholders = re.findall(r"\{[a-zA-Z_]+\}", letter_hi)
    if brace_placeholders:
        return False, f"Unreplaced brace placeholders found: {brace_placeholders}"

    # Check 4: No [bracket] template placeholders
    bracket_placeholders = re.findall(r"\[[^\]]{1,40}\]", letter_hi)
    if bracket_placeholders:
        return False, f"Unreplaced bracket placeholders found: {bracket_placeholders}"

    return True, "All checks passed."


async def _generate_letters(prompt_en: str, prompt_hi: str) -> tuple[str, str]:
    """
    Fire English and Hindi LLM calls concurrently with asyncio.gather().
    Both are independent — no reason to run sequentially.

    ainvoke is the async counterpart of invoke; both return AIMessage.
    Reference: https://python.langchain.com/docs/concepts/runnables/#async-support
    """
    llm = get_llm()
    response_en, response_hi = await asyncio.gather(
        llm.ainvoke([HumanMessage(content=prompt_en)]),
        llm.ainvoke([HumanMessage(content=prompt_hi)]),
    )
    return response_en.content.strip(), response_hi.content.strip()


def explainer_node(state: UnderwritingState) -> dict:
    """
    Generate bilingual explanation letters for the final decision.

    Node is SYNCHRONOUS (required for graph.stream() / graph.invoke()).
    Parallel LLM calls are preserved via asyncio.gather() inside _run_async().

    _run_async() detects whether a parent event loop is already running
    (pytest-asyncio, Jupyter) and dispatches to a ThreadPoolExecutor in
    that case, so asyncio.run() always executes in a loop-free thread.
    """
    decision = state.get("decision", "Reject")
    final_decision = state.get("hitl_decision") or decision

    logger.info("[Agent 6: Explainer] Generating letters for %s decision", final_decision)

    reasons_text = "\n".join(f"- {r}" for r in state.get("decision_reasons", []))

    prompt_en = _EXPLAINER_PROMPT_EN.format(
        name=state["applicant_name"],
        decision=final_decision,
        loan_amount=state["loan_amount_requested"],
        purpose=state.get("loan_purpose", "General"),
        reasons=reasons_text,
    )

    prompt_hi = _EXPLAINER_PROMPT_HI.format(
        name=state["applicant_name"],
        decision_hi=_DECISION_HI.get(final_decision, final_decision),
        loan_amount=state["loan_amount_requested"],
        purpose=state.get("loan_purpose", "सामान्य"),
        reasons=reasons_text,
    )

    # _run_async() — runs the coroutine safely regardless of context.
    #
    # Context A — Streamlit ScriptRunner thread (normal app usage):
    #   Streamlit runs each page script in a dedicated OS thread separate
    #   from Tornado's main-thread event loop. That thread has no loop of
    #   its own. asyncio.get_running_loop() raises RuntimeError here, so we
    #   fall to the except branch and call asyncio.run() directly — correct.
    #
    # Context B — pytest-asyncio / Jupyter / any async test runner:
    #   The calling thread already has a running event loop.
    #   asyncio.get_running_loop() succeeds, so we dispatch to a fresh OS
    #   thread via ThreadPoolExecutor. That thread has no parent loop, so
    #   asyncio.run() is safe there.
    #
    # References:
    #   https://docs.python.org/3/library/asyncio-runner.html
    #   https://github.com/streamlit/streamlit/issues/8488
    def _run_async(coro):
        try:
            asyncio.get_running_loop()
            # A running loop exists (pytest-asyncio, Jupyter) — dispatch to
            # a new thread so asyncio.run() has a clean loop there.
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
                return pool.submit(asyncio.run, coro).result()
        except RuntimeError:
            # No running loop on this thread (Streamlit ScriptRunner, plain
            # scripts) — safe to call asyncio.run() directly.
            return asyncio.run(coro)

    letter_en, letter_hi = _run_async(_generate_letters(prompt_en, prompt_hi))

    # ── Post-process: replace bracketed name placeholders before judge ─────
    # LLaMA 3.3-70B occasionally outputs [आपका नाम] (or English variants) as a
    # template placeholder instead of the actual applicant name, even when the
    # name is explicitly provided in the prompt. This is a known LLM behaviour
    # at low temperature — the model sometimes mirrors training-data template
    # patterns rather than substituting the variable.
    #
    # Fix: replace any [आपका नाम]-style bracketed placeholder with the real name
    # BEFORE the judge evaluates the letter. This is deterministic and avoids
    # wasting the fallback on an otherwise-correct letter that just has a name
    # substitution failure. The regex catches common variants:
    #   [आपका नाम], [आवेदक का नाम], [Your Name], [Applicant Name]
    applicant_name = state["applicant_name"]
    _name_placeholder = re.compile(
        r'\[(?:आपका नाम|आवेदक का नाम|Your Name|Applicant Name|applicant name)\]',
        flags=re.IGNORECASE,
    )
    cleaned_hi = _name_placeholder.sub(applicant_name, letter_hi)
    if cleaned_hi != letter_hi:
        logger.info(
            "[Explainer] Replaced bracketed name placeholder with '%s' in Hindi letter.",
            applicant_name,
        )
        letter_hi = cleaned_hi

    logger.info(
        "[Explainer] Letters generated concurrently. EN=%d chars, HI=%d chars",
        len(letter_en), len(letter_hi),
    )

    # ── Hindi quality verification (deterministic Python checks) ──────────
    # Check that the Hindi letter is in Devanagari, contains the right
    # decision word, and has no unreplaced placeholders.
    # On failure: log a warning and substitute the pre-written fallback.
    # On judge error: accept the generated letter (no silent replacement).
    hi_passed, hi_reason = _verify_hindi_quality(letter_hi, final_decision)
    if not hi_passed:
        logger.warning(
            "[Explainer] Hindi quality check FAILED (%s). "
            "Substituting guaranteed-correct fallback template.",
            hi_reason,
        )
        letter_hi = _HINDI_FALLBACK.get(final_decision, _HINDI_FALLBACK["Reject"])
    else:
        logger.info("[Explainer] Hindi quality check PASSED (%s).", hi_reason)

    return {
        "explanation_en": letter_en,
        "explanation_hi": letter_hi,
        "final_decision": final_decision,
    }
